=== TeenageJob/study_framework/smart/src/ty/business/org/mvc/ty/resource/xsd/jurisdiction.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<ty:schema xmlns:ty="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3school.com.cn" 
	xmlns="http://www.w3school.com.cn"
	elementFormDefault="qualified">

	<!-- 角色设置 -->
	<ty:element name="root">
		<ty:complexType>
			<ty:sequence>
				<ty:element ref="any" maxOccurs="unbounded" />
				<ty:element ref="role" maxOccurs="unbounded" />
				<ty:element ref="perm" maxOccurs="unbounded" />
			</ty:sequence>
		</ty:complexType>
	</ty:element>


	<!-- Any设置 -->
	<ty:element name="any">
		<ty:complexType>
			<ty:attribute name="url" type="ty:token" />
			<ty:attribute name="filter" type="ty:token" />
		</ty:complexType>
	</ty:element>

	<!-- 角色设置 -->
	<ty:element name="role">
		<ty:complexType>
			<ty:attribute name="url" type="ty:token" />
			<ty:attribute name="perm" type="ty:token" />
		</ty:complexType>
	</ty:element>
	<!-- 权限设置 -->
	<ty:element name="perm">
		<ty:complexType>
			<ty:attribute name="url" type="ty:token" />
			<ty:attribute name="perm" type="ty:token" />
		</ty:complexType>
	</ty:element>
</ty:schema>

=== TeenageJob/study_framework/smart/src/main/resources/shiro.xml
<?xml version='1.0' encoding='UTF-8'?>
<root xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.w3school.com.cn jurisdiction.xsd">

    <!-- cas配置 -->
    <any url="/common/login.do" filter="cas"/>
    <any url="/logout.do" filter="logout"/>
    <!-- 配置游客权限 -->

    <!-- 配置认证 -->
    <!-- 静态文件访问控制 -->
    <any url="/www/*" filter="anon"/>
    <any url="/common/register.do" filter="anon"/>
    <any url="/common/unauthorized.do" filter="anon"/>

    <!-- anon，authcBasic，auchc，user是认证过滤器 
        perms，roles，ssl，rest，port是授权过滤器 -->
    <!-- 配置授权 -->
    <!-- 配置角色 -->
    <role url="/a/*" perm="admin,super_admin"/>
    <role url="/b/*" perm="salesmane"/>

    <role url="/**" perm="ROLE_USER"/>
    <!-- 配置url权限 -->

</root>
